"""initial schema

Revision ID: b387adb2d9b8
Revises: 
Create Date: 2026-06-01 17:07:41.219739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b387adb2d9b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name_uk', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('studios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('discord_id', sa.String(length=100), nullable=True),
    sa.Column('telegram_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('discord_id'),
    sa.UniqueConstraint('telegram_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('anime',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('title_uk', sa.String(length=500), nullable=False),
    sa.Column('title_en', sa.String(length=500), nullable=False),
    sa.Column('title_jp', sa.String(length=500), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('episodes_count', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('age_rating', sa.String(length=10), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('runtime', sa.String(length=20), nullable=True),
    sa.Column('season_uk', sa.String(length=100), nullable=True),
    sa.Column('season_en', sa.String(length=100), nullable=True),
    sa.Column('synopsis_uk', sa.Text(), nullable=True),
    sa.Column('synopsis_en', sa.Text(), nullable=True),
    sa.Column('cover_url', sa.String(length=500), nullable=True),
    sa.Column('palette', sa.JSON(), nullable=True),
    sa.Column('accent', sa.String(length=20), nullable=True),
    sa.Column('studio_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('anime', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_anime_rating'), ['rating'], unique=False)
        batch_op.create_index(batch_op.f('ix_anime_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_anime_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_anime_studio_id'), ['studio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_anime_year'), ['year'], unique=False)

    op.create_table('anime_badges',
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('badge_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['anime.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('anime_id', 'badge_id')
    )
    op.create_table('anime_genres',
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['anime.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('anime_id', 'genre_id')
    )
    op.create_table('episodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('season_number', sa.Integer(), nullable=False),
    sa.Column('episode_number', sa.Integer(), nullable=False),
    sa.Column('title_uk', sa.String(length=500), nullable=True),
    sa.Column('title_en', sa.String(length=500), nullable=True),
    sa.Column('description_uk', sa.Text(), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('duration_min', sa.Integer(), nullable=True),
    sa.Column('air_date', sa.Date(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('is_filler', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['anime_id'], ['anime.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anime_id', 'season_number', 'episode_number', name='uq_anime_episode')
    )
    with op.batch_alter_table('episodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_episodes_anime_id'), ['anime_id'], unique=False)

    op.create_table('user_anime',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['anime_id'], ['anime.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'anime_id', name='uq_user_anime')
    )
    with op.batch_alter_table('user_anime', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_anime_anime_id'), ['anime_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_anime_user_id'), ['user_id'], unique=False)

    op.create_table('watch_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=True),
    sa.Column('season_number', sa.Integer(), nullable=False),
    sa.Column('episode_number', sa.Integer(), nullable=False),
    sa.Column('watched_seconds', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['anime_id'], ['anime.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'anime_id', 'season_number', 'episode_number', name='uq_watch_progress')
    )
    with op.batch_alter_table('watch_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watch_progress_anime_id'), ['anime_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_watch_progress_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watch_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watch_progress_user_id'))
        batch_op.drop_index(batch_op.f('ix_watch_progress_anime_id'))

    op.drop_table('watch_progress')
    with op.batch_alter_table('user_anime', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_anime_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_anime_anime_id'))

    op.drop_table('user_anime')
    with op.batch_alter_table('episodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_episodes_anime_id'))

    op.drop_table('episodes')
    op.drop_table('anime_genres')
    op.drop_table('anime_badges')
    with op.batch_alter_table('anime', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_anime_year'))
        batch_op.drop_index(batch_op.f('ix_anime_studio_id'))
        batch_op.drop_index(batch_op.f('ix_anime_status'))
        batch_op.drop_index(batch_op.f('ix_anime_slug'))
        batch_op.drop_index(batch_op.f('ix_anime_rating'))

    op.drop_table('anime')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('studios')
    op.drop_table('genres')
    op.drop_table('badges')
    # ### end Alembic commands ###
